--------------------------------------------------------
--  DDL for Table ADDITIONAL_CONTACT
--------------------------------------------------------

  CREATE TABLE "BPM_MICROLOAN"."ADDITIONAL_CONTACT"
   (	"ID" NUMBER(19,2),
	"BIRTH_DATE" DATE,
	"FIO" VARCHAR2(255 CHAR),
	"PHONE" VARCHAR2(255 CHAR),
	"RELATION_TYPE" VARCHAR2(255 CHAR),
	"APPLICATION_ID" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MICROLOAN_DATA" ;
--------------------------------------------------------
--  DDL for Table ADDITIONAL_INCOME
--------------------------------------------------------

  CREATE TABLE "BPM_MICROLOAN"."ADDITIONAL_INCOME"
   (	"ID" NUMBER(19,2),
	"INCOME_TYPE" VARCHAR2(255 CHAR),
	"SUM" NUMBER(19,0),
	"REL_PERSON_ID" NUMBER(19,2),
	"CLIENT_ID" NUMBER(19,2)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MICROLOAN_DATA" ;
--------------------------------------------------------
--  DDL for Table ADDRESS
--------------------------------------------------------

  CREATE TABLE "BPM_MICROLOAN"."ADDRESS"
   (	"ID" NUMBER(19,2),
	"ACTIVE_FLAG" VARCHAR2(255 CHAR),
	"ADDRESS_LINE" VARCHAR2(2000 CHAR),
	"ADDRESS_TYPE" VARCHAR2(255 CHAR),
	"APARTMENT" VARCHAR2(255 CHAR),
	"BUILDING" VARCHAR2(255 CHAR),
	"CITY" VARCHAR2(255 CHAR),
	"CITY_CODE" VARCHAR2(255 CHAR),
	"CITY_TYPE" VARCHAR2(255 CHAR),
	"COUNTRY" VARCHAR2(255 CHAR),
	"DISTRICT" VARCHAR2(255 CHAR),
	"DISTRICT_CODE" VARCHAR2(255 CHAR),
	"DISTRICT_TYPE" VARCHAR2(255 CHAR),
	"FLAT_CODE" VARCHAR2(255 CHAR),
	"FORMAT" VARCHAR2(255 CHAR),
	"HOUSE" VARCHAR2(255 CHAR),
	"HOUSE_CODE" VARCHAR2(255 CHAR),
	"HOUSE_TYPE" VARCHAR2(255 CHAR),
	"POSTAL_CODE" VARCHAR2(255 CHAR),
	"REGION" VARCHAR2(255 CHAR),
	"REGION_CODE" VARCHAR2(255 CHAR),
	"REGION_TYPE" VARCHAR2(255 CHAR),
	"SETTLEMENT" VARCHAR2(255 CHAR),
	"SETTLEMENT_CODE" VARCHAR2(255 CHAR),
	"SETTLEMENT_TYPE" VARCHAR2(255 CHAR),
	"STATE" VARCHAR2(255 CHAR),
	"STREET" VARCHAR2(255 CHAR),
	"STREET_CODE" VARCHAR2(255 CHAR),
	"STREET_TYPE" VARCHAR2(255 CHAR),
	"REL_PERSON_ID" NUMBER(19,2),
	"CLIENT_ID" NUMBER(19,2)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MICROLOAN_DATA" ;

  --------------------------------------------------------
--  DDL for Table SOLVENCY_TYPE
--------------------------------------------------------
  CREATE TABLE "BPM_MICROLOAN"."SOLVENCY_TYPE"
   (	"ID" NUMBER(19,2) NOT NULL ENABLE,
	"AMOUNT" NUMBER(19,2),
	"COBORROWER" VARCHAR2(255 CHAR),
	"CONTRACT_END_DATE" DATE,
	"INTEREST_RATE" NUMBER(19,2),
	"LOAN_TERM" VARCHAR2(255 CHAR),
	"LOAN_TERM_INTERVAL" VARCHAR2(255 CHAR),
	"LOAN_TERM_INTERVAL_NAME" VARCHAR2(255 CHAR),
	"LOAN_TERM_NAME" VARCHAR2(255 CHAR),
	"TERM" NUMBER(10,0),
	"TYPE_OFFER_CODE" VARCHAR2(255 CHAR),
	"TYPE_OFFER_TEXT" VARCHAR2(255 CHAR),
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  TABLESPACE "MICROLOAN_DATA"  ENABLE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "MICROLOAN_DATA";

--------------------------------------------------------
--  DDL for Table SCORING_TYPE
--------------------------------------------------------

CREATE TABLE "BPM_MICROLOAN"."SCORING_TYPE"
   (	"ID" NUMBER(19,2) NOT NULL ENABLE,
	"CREDIT_HISTORY_DATA" VARCHAR2(255 CHAR),
	"DM0_RESULT" NUMBER(10,0),
	"DM1_RESULT" NUMBER(10,0),
	"DM2_RESULT" NUMBER(10,0),
	"DM3_RESULT" NUMBER(10,0),
	"DM4_RESULT" NUMBER(10,0),
	"INCOME_TAX_DATA" VARCHAR2(255 CHAR),
	"REJECT_REASON" VARCHAR2(255 CHAR),
	"REJECT_REASON_NIKI" VARCHAR2(255 CHAR),
	"SCORE_DATA" VARCHAR2(255 CHAR),
	"SOLVENCY_ID" NUMBER(19,2),
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  TABLESPACE "MICROLOAN_DATA"  ENABLE,
	 CONSTRAINT "UK_J10MH1UMSH6JB6VDJ16QIQTR1" UNIQUE ("SOLVENCY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "MICROLOAN_DATA"  ENABLE,
	 CONSTRAINT "FKMRIFKI5XQUAFUSCXSWF6UE8ED" FOREIGN KEY ("SOLVENCY_ID")
	  REFERENCES "BPM_MICROLOAN"."SOLVENCY_TYPE" ("ID") ENABLE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "MICROLOAN_DATA";

--------------------------------------------------------
--  DDL for Table APPLICATION
--------------------------------------------------------
CREATE TABLE "BPM_MICROLOAN"."APPLICATION"
   (	"APPLICATION_ID" NUMBER(19,2) NOT NULL ENABLE,
	"BRANCH" VARCHAR2(255 CHAR),
	"CLIME_DATE" TIMESTAMP (6),
	"CLAIM_NUM_ABS" VARCHAR2(255 CHAR),
	"CLAIM_NUM_BPM" VARCHAR2(255 CHAR),
	"CLAIM_NUM_CRM" VARCHAR2(255 CHAR),
	"DESICION" VARCHAR2(255 CHAR),
	"MANAGER_NAME" VARCHAR2(255 CHAR),
	"STATUS" VARCHAR2(255 CHAR),
	"CLIENT_ID" NUMBER(19,2),
	"CREDIT_ADMINISTRATOR_COMMENT_ID" NUMBER(19,2),
	"INSURANCE_ID" NUMBER(19,2),
	"LOAN_ID" NUMBER(19,2),
	"VERIFICATION_COMMENT_ID" NUMBER(19,2),
	 PRIMARY KEY ("APPLICATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MICROLOAN_DATA"  ENABLE,
	 CONSTRAINT "UK_HBIKCJNCWPH3TKM4CKP713F4E" UNIQUE ("CLIENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MICROLOAN_DATA"  ENABLE,
	 CONSTRAINT "UK_OFSI4BR5POT63UMDTTEJ2SQY1" UNIQUE ("CREDIT_ADMINISTRATOR_COMMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MICROLOAN_DATA"  ENABLE,
	 CONSTRAINT "UK_AY81UMWAFERMRAB2TUXKRSFPL" UNIQUE ("INSURANCE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MICROLOAN_DATA"  ENABLE,
	 CONSTRAINT "UK_FWEUL14X99QIFNANE8Y339CQT" UNIQUE ("LOAN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MICROLOAN_DATA"  ENABLE,
	 CONSTRAINT "UK_EF61U7GYJXFBS13PU6M0S13D9" UNIQUE ("VERIFICATION_COMMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MICROLOAN_DATA"  ENABLE,
	 CONSTRAINT "FKDGOPRC28QXV8RXIVN0O2MBO7U" FOREIGN KEY ("CLIENT_ID")
	  REFERENCES "BPM_MICROLOAN"."CLIENT" ("ID") ENABLE,
	 CONSTRAINT "FK5HADTT8WQCFSS29012FY88VLM" FOREIGN KEY ("CREDIT_ADMINISTRATOR_COMMENT_ID")
	  REFERENCES "BPM_MICROLOAN"."APP_COMMENTS" ("ID") ENABLE,
	 CONSTRAINT "FKCSMWWCS3H21EOIWIVU6YYNNCS" FOREIGN KEY ("INSURANCE_ID")
	  REFERENCES "BPM_MICROLOAN"."INSURANCE" ("ID") ENABLE,
	 CONSTRAINT "FKCSGAQ1AUJC4G7RGNKUP5HH2J3" FOREIGN KEY ("LOAN_ID")
	  REFERENCES "BPM_MICROLOAN"."LOAN" ("ID") ENABLE,
	 CONSTRAINT "FKPU60A4BOK8R2PUMUCANJXYPUH" FOREIGN KEY ("VERIFICATION_COMMENT_ID")
	  REFERENCES "BPM_MICROLOAN"."APP_COMMENTS" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MICROLOAN_DATA";

--------------------------------------------------------
--  DDL for Table APPLICATION_HISTORY
--------------------------------------------------------

  CREATE TABLE "BPM_MICROLOAN"."APPLICATION_HISTORY"
   (	"ID" NUMBER(19,2),
	"CHANGE_USER" VARCHAR2(255 CHAR),
	"COMMENT_TEXT" VARCHAR2(255 CHAR),
	"CREATE_USER" VARCHAR2(255 CHAR),
	"CURRENT_STATUS" VARCHAR2(255 CHAR),
	"DATE_TIME_CHANGE" TIMESTAMP (6),
	"DATE_TIME_CREATE" TIMESTAMP (6),
	"DATE_TIME_DELETE" TIMESTAMP (6),
	"DELETE_USER" VARCHAR2(255 CHAR),
	"TASK_NAME" VARCHAR2(255 CHAR),
	"APPLICATION_ID" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "MICROLOAN_DATA" ;
--------------------------------------------------------
--  DDL for Table ATTACHED_DOCUMENT
--------------------------------------------------------

  CREATE TABLE "BPM_MICROLOAN"."ATTACHED_DOCUMENT"
   (	"ID" NUMBER(19,2),
	"DOCUMENT_DATE" DATE,
	"DOCUMENT_NAME" VARCHAR2(255 CHAR),
	"DOCUMENT_TYPE" VARCHAR2(255 CHAR),
	"GUID" VARCHAR2(255 CHAR),
	"OPERATION_TYPE" VARCHAR2(255 CHAR),
	"APPLICATION_ID" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MICROLOAN_DATA" ;
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------
CREATE TABLE "BPM_MICROLOAN"."CLIENT"
   (	"ID" NUMBER(19,2) NOT NULL ENABLE,
	"ADULT_CHILDREN_NUM" NUMBER(10,0),
	"BIRTH_DATE" DATE,
	"CHILDREN_NUM_0_TO_3" NUMBER(10,0),
	"CHILDREN_NUM_3_TO_16" NUMBER(10,0),
	"CITIZENSHIP" VARCHAR2(255 CHAR),
	"CLIENT_CODE" VARCHAR2(255 CHAR),
	"CLIENT_CODE_CRM" VARCHAR2(255 CHAR),
	"CLIENT_ABS_ID" VARCHAR2(255 CHAR),
	"CLIENT_ABS_UID" VARCHAR2(255 CHAR),
	"EDUCATION" VARCHAR2(255 CHAR),
	"FINAL_RISK_LEVEL" VARCHAR2(255 CHAR),
	"FIRST_NAME" VARCHAR2(255 CHAR),
	"FULL_NAME" VARCHAR2(255 CHAR),
	"INN" VARCHAR2(255 CHAR),
	"IS_ADDITIONAL_INCOME" NUMBER(1,0),
	"IS_CAR" NUMBER(1,0),
	"IS_CO_BORROWED" NUMBER(1,0),
	"IS_GUARANTOR" NUMBER(1,0),
	"IS_REAL_ESTATE" NUMBER(1,0),
	"IS_RETIREE" NUMBER(1,0),
	"LAST_NAME" VARCHAR2(255 CHAR),
	"MARITAL_STATUS" VARCHAR2(255 CHAR),
	"NINPS_ACCOUNT" VARCHAR2(255 CHAR),
	"PATRONYMIC" VARCHAR2(255 CHAR),
	"PINFL" VARCHAR2(255 CHAR),
	"BIRTH_PLACE" VARCHAR2(255 CHAR),
	"REG_ADDR_EQ_RES_ADDR" NUMBER(1,0),
	"GENDER" VARCHAR2(255 CHAR),
	"TYPE_OF_HOUSING" VARCHAR2(255 CHAR),
	"JOB_INFO_ID" NUMBER(19,2),
	"SCORING_ID" NUMBER(19,2),
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MICROLOAN_DATA"  ENABLE,
	 CONSTRAINT "UK_CG16HW08FBP3O6EWI46QBLTWN" UNIQUE ("JOB_INFO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MICROLOAN_DATA"  ENABLE,
	 CONSTRAINT "UK_6OC5RG0SQLSAIWP5MKECH3QRV" UNIQUE ("SCORING_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MICROLOAN_DATA"  ENABLE,
	 CONSTRAINT "FKQFW515EXNN3FP800W0GW6WVKT" FOREIGN KEY ("JOB_INFO_ID")
	  REFERENCES "BPM_MICROLOAN"."JOB_INFO" ("ID") ENABLE,
	 CONSTRAINT "FKN0TVWM3T883KXUSUH336TXQBX" FOREIGN KEY ("SCORING_ID")
	  REFERENCES "BPM_MICROLOAN"."SCORING_TYPE" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MICROLOAN_DATA";



--------------------------------------------------------
--  DDL for Table CURRENT_LOAN
--------------------------------------------------------

  CREATE TABLE "BPM_MICROLOAN"."CURRENT_LOAN"
   (	"ID" NUMBER(19,2),
	"CREDIT_BANK" VARCHAR2(255 CHAR),
	"MONTHLY_PAYMENT" NUMBER(19,0),
	"SUM" NUMBER(19,0),
	"REL_PERSON_ID" NUMBER(19,2),
	"CLIENT_ID" NUMBER(19,2)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MICROLOAN_DATA" ;
--------------------------------------------------------
--  DDL for Table DEPOSIT_INFO
--------------------------------------------------------

  CREATE TABLE "BPM_MICROLOAN"."DEPOSIT_INFO"
   (	"ID" NUMBER(19,2),
	"BANK" VARCHAR2(255 CHAR),
	"SUM" NUMBER(19,0),
	"REL_PERSON_ID" NUMBER(19,2),
	"CLIENT_ID" NUMBER(19,2)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MICROLOAN_DATA" ;
--------------------------------------------------------
--  DDL for Table DOCUMENT
--------------------------------------------------------

  CREATE TABLE "BPM_MICROLOAN"."DOCUMENT"
   (	"ID" NUMBER(19,2),
	"DIVISION_CODE" VARCHAR2(255 CHAR),
	"DOCUMENT_NAME" VARCHAR2(255 CHAR),
	"IDENTIFICATION_FLAG" NUMBER(1,0),
	"ISSUE_DATE" DATE,
	"ISSUED" VARCHAR2(255 CHAR),
	"DOCUMENT_NUMBER" VARCHAR2(255 CHAR),
	"SERIES" VARCHAR2(255 CHAR),
	"TYPE" VARCHAR2(255 CHAR),
	"REL_PERSON_ID" NUMBER(19,2),
	"CLIENT_ID" NUMBER(19,2)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MICROLOAN_DATA" ;
--------------------------------------------------------
--  DDL for Table INSURANCE
--------------------------------------------------------

  CREATE TABLE "BPM_MICROLOAN"."INSURANCE"
   (	"ID" NUMBER(19,2),
	"CONTRACT_ID" VARCHAR2(255 CHAR),
	"INSURANCE_COMPANY" VARCHAR2(255 CHAR),
	"LIABILITY" VARCHAR2(255 CHAR),
	"PAYMENT_DATE" DATE,
	"POLICY_SERIES" VARCHAR2(255 CHAR),
	"POLICY_NUMBER" VARCHAR2(255 CHAR),
	"PREMIUM_FROM_CREDIT_FUNDS" NUMBER(1,0),
	"PREMIUM_FROM_OWN_FUNDS" NUMBER(1,0),
	"PREMIUM_SUM" NUMBER(19,0)
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "MICROLOAN_DATA" ;
--------------------------------------------------------
--  DDL for Table JOB_INFO
--------------------------------------------------------

  CREATE TABLE "BPM_MICROLOAN"."JOB_INFO"
   (	"ID" NUMBER(19,2),
	"BANK_SALARY" VARCHAR2(255 CHAR),
	"EMPLOYER_ACTIVITY_TYPE" VARCHAR2(255 CHAR),
	"EMPLOYER_NAME" VARCHAR2(255 CHAR),
	"INN" VARCHAR2(255 CHAR),
	"LAST_JOB_EXPERIENCE" NUMBER(10,0),
	"MONTHLY_SALARY" NUMBER(19,0),
	"PHONE" VARCHAR2(255 CHAR),
	"POSITION" VARCHAR2(255 CHAR),
	"START_JOB_DATE" DATE,
	"TOTAL_JOB_EXPERIENCE" NUMBER(10,0),
	"TYPE" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MICROLOAN_DATA" ;
--------------------------------------------------------
--  DDL for Table LOAN
--------------------------------------------------------

  CREATE TABLE "BPM_MICROLOAN"."LOAN"
   (	"ID" NUMBER(19,2),
	"COLLATERAL_TYPE" VARCHAR2(255 CHAR),
	"CURRENCY" VARCHAR2(255 CHAR),
	"FACILITATE_FOR_REPAYMENT_DATE" NUMBER(1,0),
	"INITIAL_PAYMENT" NUMBER(19,0),
	"INSURANCE_FROM_CREDIT_FUNDS" NUMBER(1,0),
	"INSURANCE_FROM_OWN_FUNDS" NUMBER(1,0),
	"INTEREST_RATE" NUMBER(19,2),
	"ISSUANCE_FORM" VARCHAR2(255 CHAR),
	"LOAN_PRODUCT" VARCHAR2(255 CHAR),
	"LOAN_PURPOSE" VARCHAR2(255 CHAR),
	"MAX_DEF_REPAYMENT_PERIOD" NUMBER(10,0),
	"MAX_INITIAL_PAYMENT" NUMBER(19,0),
	"MAX_INTEREST_RATE" NUMBER(19,0),
	"MIN_INITIAL_PAYMENT" NUMBER(19,0),
	"MIN_INTEREST_RATE" NUMBER(19,0),
	"PRODUCT_ID" VARCHAR2(255 CHAR),
	"REPAYMENT_DAY" NUMBER(10,0),
	"REPAYMENT_TYPE" VARCHAR2(255 CHAR),
	"START_DATE" DATE,
	"SUM" NUMBER(19,0),
	"TERM_IN_MONTH" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MICROLOAN_DATA" ;
--------------------------------------------------------
--  DDL for Table PHONE_INFO
--------------------------------------------------------

  CREATE TABLE "BPM_MICROLOAN"."PHONE_INFO"
   (	"ID" NUMBER(19,2),
	"ADD_PHONE_NUMBER" VARCHAR2(255 CHAR),
	"COUNTRY_PREFIX" VARCHAR2(255 CHAR),
	"PHONE_NUMBER" VARCHAR2(255 CHAR),
	"PHONE_STATUS" VARCHAR2(255 CHAR),
	"PRIMARY_PHONE" NUMBER(1,0),
	"TYPE" VARCHAR2(255 CHAR),
	"REL_PERSON_ID" NUMBER(19,2),
	"CLIENT_ID" NUMBER(19,2)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MICROLOAN_DATA" ;
--------------------------------------------------------
--  DDL for Table RELATED_PERSON
--------------------------------------------------------
CREATE TABLE "BPM_MICROLOAN"."RELATED_PERSON"
   (	"ID" NUMBER(19,2) NOT NULL ENABLE,
	"TYPE_OF_HOUSING" VARCHAR2(255 CHAR),
	"ADULT_CHILDREN_NUM" NUMBER(10,0),
	"BIRTH_DATE" DATE,
	"CHILDREN_NUM_0_TO_3" NUMBER(10,0),
	"CHILDREN_NUM_3_TO_16" NUMBER(10,0),
	"CITIZENSHIP" VARCHAR2(255 CHAR),
	"CLIENT_CODE" VARCHAR2(255 CHAR),
	"CLIENT_CODE_CRM" VARCHAR2(255 CHAR),
	"CLIENT_ABS_ID" VARCHAR2(255 CHAR),
	"CLIENT_ABS_UID" VARCHAR2(255 CHAR),
	"EDUCATION" VARCHAR2(255 CHAR),
	"FINAL_RISK_LEVEL" VARCHAR2(255 CHAR),
	"FIRST_NAME" VARCHAR2(255 CHAR),
	"FULL_NAME" VARCHAR2(255 CHAR),
	"INN" VARCHAR2(255 CHAR),
	"IS_ADDITIONAL_INCOME" NUMBER(1,0),
	"IS_CAR" NUMBER(1,0),
	"IS_REAL_ESTATE" NUMBER(1,0),
	"IS_RETIREE" NUMBER(1,0),
	"LAST_NAME" VARCHAR2(255 CHAR),
	"MARITAL_STATUS" VARCHAR2(255 CHAR),
	"NINPS_ACCOUNT_BANK" VARCHAR2(255 CHAR),
	"PATRONYMIC" VARCHAR2(255 CHAR),
	"PINFL" VARCHAR2(255 CHAR),
	"BIRTH_PLACE" VARCHAR2(255 CHAR),
	"REG_ADDR_EQ_RES_ADDR" NUMBER(1,0),
	"GENDER" VARCHAR2(255 CHAR),
	"TRUSTEE_STATUS" VARCHAR2(255 CHAR),
	"JOB_INFO_ID" NUMBER(19,2),
	"SCORING_ID" NUMBER(19,2),
	"CLIENT_ID" NUMBER(19,2),
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MICROLOAN_DATA"  ENABLE,
	 CONSTRAINT "UK_CLNQ7RYKCNLMQKFNYGH52YFLV" UNIQUE ("JOB_INFO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MICROLOAN_DATA"  ENABLE,
	 CONSTRAINT "UK_77I85CTPD9IW72OVENE62XWJV" UNIQUE ("SCORING_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MICROLOAN_DATA"  ENABLE,
	 CONSTRAINT "FK9I8SRGPQFEJV2STSVB45HYTIH" FOREIGN KEY ("JOB_INFO_ID")
	  REFERENCES "BPM_MICROLOAN"."JOB_INFO" ("ID") ENABLE,
	 CONSTRAINT "FKFXHWAWUNPEALVG72X4C9KAJ29" FOREIGN KEY ("SCORING_ID")
	  REFERENCES "BPM_MICROLOAN"."SCORING_TYPE" ("ID") ENABLE,
	 CONSTRAINT "FK5KWJV4MDH9L694S4ITV8BKL98" FOREIGN KEY ("CLIENT_ID")
	  REFERENCES "BPM_MICROLOAN"."CLIENT" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MICROLOAN_DATA";







   CREATE SEQUENCE  "BPM_MICROLOAN"."SEQ_APPLICATION"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

--------------------------------------------------------
--  DDL for Sequence SEQ_ADDINCOME
--------------------------------------------------------

   CREATE SEQUENCE  "BPM_MICROLOAN"."SEQ_ADDINCOME"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ADDITIONAL_CONTACT
--------------------------------------------------------

   CREATE SEQUENCE  "BPM_MICROLOAN"."SEQ_ADDITIONAL_CONTACT"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ADDRESS
--------------------------------------------------------

   CREATE SEQUENCE  "BPM_MICROLOAN"."SEQ_ADDRESS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_APPLICATION_HISTORY
--------------------------------------------------------

   CREATE SEQUENCE  "BPM_MICROLOAN"."SEQ_APPLICATION_HISTORY"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ATTACHED_DOCUMENT
--------------------------------------------------------

   CREATE SEQUENCE  "BPM_MICROLOAN"."SEQ_ATTACHED_DOCUMENT"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CLIENT
--------------------------------------------------------

   CREATE SEQUENCE  "BPM_MICROLOAN"."SEQ_CLIENT"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_COMMENT
--------------------------------------------------------

   CREATE SEQUENCE  "BPM_MICROLOAN"."SEQ_COMMENT"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CURRENT_LOAN
--------------------------------------------------------

   CREATE SEQUENCE  "BPM_MICROLOAN"."SEQ_CURRENT_LOAN"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_DEPOSIT_INFO
--------------------------------------------------------

   CREATE SEQUENCE  "BPM_MICROLOAN"."SEQ_DEPOSIT_INFO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_DOCUMENT
--------------------------------------------------------

   CREATE SEQUENCE  "BPM_MICROLOAN"."SEQ_DOCUMENT"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_INSURANCE
--------------------------------------------------------

   CREATE SEQUENCE  "BPM_MICROLOAN"."SEQ_INSURANCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_JOB_INFO
--------------------------------------------------------

   CREATE SEQUENCE  "BPM_MICROLOAN"."SEQ_JOB_INFO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_LOAN
--------------------------------------------------------

   CREATE SEQUENCE  "BPM_MICROLOAN"."SEQ_LOAN"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PHONE
--------------------------------------------------------

   CREATE SEQUENCE  "BPM_MICROLOAN"."SEQ_PHONE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_RELATED_PERSON
--------------------------------------------------------

   CREATE SEQUENCE  "BPM_MICROLOAN"."SEQ_RELATED_PERSON"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_SCORING_TYPE
--------------------------------------------------------

   CREATE SEQUENCE  "BPM_MICROLOAN"."SEQ_SCORING_TYPE "  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_SOLVENCY_TYPE
--------------------------------------------------------

   CREATE SEQUENCE  "BPM_MICROLOAN"."SEQ_SOLVENCY_TYPE "  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

--------------------------------------------------------
--  Constraints for Table INSURANCE
--------------------------------------------------------

  ALTER TABLE "BPM_MICROLOAN"."INSURANCE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BPM_MICROLOAN"."INSURANCE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  TABLESPACE "MICROLOAN_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ADDITIONAL_CONTACT
--------------------------------------------------------

  ALTER TABLE "BPM_MICROLOAN"."ADDITIONAL_CONTACT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BPM_MICROLOAN"."ADDITIONAL_CONTACT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MICROLOAN_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ADDRESS
--------------------------------------------------------

  ALTER TABLE "BPM_MICROLOAN"."ADDRESS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BPM_MICROLOAN"."ADDRESS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MICROLOAN_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LOAN
--------------------------------------------------------

  ALTER TABLE "BPM_MICROLOAN"."LOAN" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BPM_MICROLOAN"."LOAN" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MICROLOAN_DATA"  ENABLE;


--------------------------------------------------------
--  Constraints for Table DEPOSIT_INFO
--------------------------------------------------------

  ALTER TABLE "BPM_MICROLOAN"."DEPOSIT_INFO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BPM_MICROLOAN"."DEPOSIT_INFO" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MICROLOAN_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ATTACHED_DOCUMENT
--------------------------------------------------------

  ALTER TABLE "BPM_MICROLOAN"."ATTACHED_DOCUMENT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BPM_MICROLOAN"."ATTACHED_DOCUMENT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MICROLOAN_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table JOB_INFO
--------------------------------------------------------

  ALTER TABLE "BPM_MICROLOAN"."JOB_INFO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BPM_MICROLOAN"."JOB_INFO" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MICROLOAN_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CURRENT_LOAN
--------------------------------------------------------

  ALTER TABLE "BPM_MICROLOAN"."CURRENT_LOAN" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BPM_MICROLOAN"."CURRENT_LOAN" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MICROLOAN_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DOCUMENT
--------------------------------------------------------

  ALTER TABLE "BPM_MICROLOAN"."DOCUMENT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BPM_MICROLOAN"."DOCUMENT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MICROLOAN_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ADDITIONAL_INCOME
--------------------------------------------------------

  ALTER TABLE "BPM_MICROLOAN"."ADDITIONAL_INCOME" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BPM_MICROLOAN"."ADDITIONAL_INCOME" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MICROLOAN_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PHONE_INFO
--------------------------------------------------------

  ALTER TABLE "BPM_MICROLOAN"."PHONE_INFO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BPM_MICROLOAN"."PHONE_INFO" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MICROLOAN_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table APPLICATION_HISTORY
--------------------------------------------------------

  ALTER TABLE "BPM_MICROLOAN"."APPLICATION_HISTORY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BPM_MICROLOAN"."APPLICATION_HISTORY" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  TABLESPACE "MICROLOAN_DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ADDITIONAL_CONTACT
--------------------------------------------------------

  ALTER TABLE "BPM_MICROLOAN"."ADDITIONAL_CONTACT" ADD CONSTRAINT "FK51GPN3DNWYAJRVQRSLGC6CA3K" FOREIGN KEY ("APPLICATION_ID")
	  REFERENCES "BPM_MICROLOAN"."APPLICATION" ("APPLICATION_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ADDITIONAL_INCOME
--------------------------------------------------------

  ALTER TABLE "BPM_MICROLOAN"."ADDITIONAL_INCOME" ADD CONSTRAINT "FKHHV12DCHTUI3IQAJHBY3L6MU6" FOREIGN KEY ("REL_PERSON_ID")
	  REFERENCES "BPM_MICROLOAN"."RELATED_PERSON" ("ID") ENABLE;
  ALTER TABLE "BPM_MICROLOAN"."ADDITIONAL_INCOME" ADD CONSTRAINT "FK4OXSUNRQMUFE0K5R1BW5R8YO0" FOREIGN KEY ("CLIENT_ID")
	  REFERENCES "BPM_MICROLOAN"."CLIENT" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ADDRESS
--------------------------------------------------------

  ALTER TABLE "BPM_MICROLOAN"."ADDRESS" ADD CONSTRAINT "FK5W2XSP6MOAXF2WBPIGNEYIP53" FOREIGN KEY ("REL_PERSON_ID")
	  REFERENCES "BPM_MICROLOAN"."RELATED_PERSON" ("ID") ENABLE;
  ALTER TABLE "BPM_MICROLOAN"."ADDRESS" ADD CONSTRAINT "FKQWKMU6S08B624OLY9LD8O2BNG" FOREIGN KEY ("CLIENT_ID")
	  REFERENCES "BPM_MICROLOAN"."CLIENT" ("ID") ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table APPLICATION_HISTORY
--------------------------------------------------------

  ALTER TABLE "BPM_MICROLOAN"."APPLICATION_HISTORY" ADD CONSTRAINT "FKFMY1DG0G02489L5AOGVV8CP2J" FOREIGN KEY ("APPLICATION_ID")
	  REFERENCES "BPM_MICROLOAN"."APPLICATION" ("APPLICATION_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ATTACHED_DOCUMENT
--------------------------------------------------------

  ALTER TABLE "BPM_MICROLOAN"."ATTACHED_DOCUMENT" ADD CONSTRAINT "FK5BK4OXL5ET8RI800V1E4U1FJB" FOREIGN KEY ("APPLICATION_ID")
	  REFERENCES "BPM_MICROLOAN"."APPLICATION" ("APPLICATION_ID") ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table CURRENT_LOAN
--------------------------------------------------------

  ALTER TABLE "BPM_MICROLOAN"."CURRENT_LOAN" ADD CONSTRAINT "FKELGERB96CKX3OQFITFIJ5DHOK" FOREIGN KEY ("REL_PERSON_ID")
	  REFERENCES "BPM_MICROLOAN"."RELATED_PERSON" ("ID") ENABLE;
  ALTER TABLE "BPM_MICROLOAN"."CURRENT_LOAN" ADD CONSTRAINT "FKS5RLU32I4WOEHCT71O4RNEFF1" FOREIGN KEY ("CLIENT_ID")
	  REFERENCES "BPM_MICROLOAN"."CLIENT" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DEPOSIT_INFO
--------------------------------------------------------

  ALTER TABLE "BPM_MICROLOAN"."DEPOSIT_INFO" ADD CONSTRAINT "FKERY4FQDM5KL9A5IAO1A9IL602" FOREIGN KEY ("REL_PERSON_ID")
	  REFERENCES "BPM_MICROLOAN"."RELATED_PERSON" ("ID") ENABLE;
  ALTER TABLE "BPM_MICROLOAN"."DEPOSIT_INFO" ADD CONSTRAINT "FKTIO48LQNJIBSK7SCGT0LLXI9O" FOREIGN KEY ("CLIENT_ID")
	  REFERENCES "BPM_MICROLOAN"."CLIENT" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DOCUMENT
--------------------------------------------------------

  ALTER TABLE "BPM_MICROLOAN"."DOCUMENT" ADD CONSTRAINT "FKJGCWJU1HDQY9LIC92HH6MQ6RB" FOREIGN KEY ("REL_PERSON_ID")
	  REFERENCES "BPM_MICROLOAN"."RELATED_PERSON" ("ID") ENABLE;
  ALTER TABLE "BPM_MICROLOAN"."DOCUMENT" ADD CONSTRAINT "FKDYYWKMJC37HKO1SNBL0WBLIXB" FOREIGN KEY ("CLIENT_ID")
	  REFERENCES "BPM_MICROLOAN"."CLIENT" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PHONE_INFO
--------------------------------------------------------

  ALTER TABLE "BPM_MICROLOAN"."PHONE_INFO" ADD CONSTRAINT "FKOM2BDNEOKBU00JS2RVHEANJ74" FOREIGN KEY ("REL_PERSON_ID")
	  REFERENCES "BPM_MICROLOAN"."RELATED_PERSON" ("ID") ENABLE;
  ALTER TABLE "BPM_MICROLOAN"."PHONE_INFO" ADD CONSTRAINT "FKH16I12YJ10WMOVEBOB7GW3I2R" FOREIGN KEY ("CLIENT_ID")
	  REFERENCES "BPM_MICROLOAN"."CLIENT" ("ID") ENABLE;



