CREATE TABLESPACE MICROLOAN_DATA
    DATAFILE 'tbs_microloan_data_01.dbf' SIZE 20M REUSE
    AUTOEXTEND ON NEXT 5M
    EXTENT MANAGEMENT LOCAL
    SEGMENT SPACE MANAGEMENT AUTO
    ONLINE
    PERMANENT
;

CREATE TEMPORARY TABLESPACE MICROLOAN_TEMP
    TEMPFILE 'tbs_microloan_temp_01.dbf' SIZE 20M REUSE
    AUTOEXTEND ON NEXT 5M
    EXTENT MANAGEMENT LOCAL;


CREATE USER BPM_MICROLOAN IDENTIFIED BY BPM_MICROLOAN
DEFAULT TABLESPACE "MICROLOAN_DATA"
TEMPORARY TABLESPACE "MICROLOAN_TEMP";
ALTER USER BPM_MICROLOAN QUOTA UNLIMITED ON MICROLOAN_DATA;
GRANT "RESOURCE" TO BPM_MICROLOAN;
GRANT "CONNECT" TO BPM_MICROLOAN;
GRANT CREATE VIEW TO BPM_MICROLOAN;
ALTER USER BPM_MICROLOAN DEFAULT ROLE "RESOURCE","CONNECT";
GRANT UNLIMITED TABLESPACE TO BPM_MICROLOAN;