CREATE TABLESPACE COMMON_DATA
    DATAFILE 'tbs_common_data_01.dbf' SIZE 20M REUSE
    AUTOEXTEND ON NEXT 5M
    EXTENT MANAGEMENT LOCAL
    SEGMENT SPACE MANAGEMENT AUTO
    ONLINE
    PERMANENT
;

CREATE TEMPORARY TABLESPACE COMMON_TEMP
    TEMPFILE 'tbs_common_temp_01.dbf' SIZE 20M REUSE
    AUTOEXTEND ON NEXT 5M
    EXTENT MANAGEMENT LOCAL;


CREATE USER BPM_COMMON IDENTIFIED BY BPM_COMMON
DEFAULT TABLESPACE "COMMON_DATA"
TEMPORARY TABLESPACE "COMMON_TEMP";
ALTER USER BPM_COMMON QUOTA UNLIMITED ON COMMON_DATA;
GRANT "RESOURCE" TO BPM_COMMON;
GRANT "CONNECT" TO BPM_COMMON;
GRANT CREATE VIEW TO BPM_COMMON;
ALTER USER BPM_COMMON DEFAULT ROLE "RESOURCE","CONNECT";
GRANT UNLIMITED TABLESPACE TO BPM_COMMON;