//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.21 at 03:55:05 PM MSK 
//


package ru.digitalspirit.asaka.microloan.model;

import java.math.BigInteger;
import java.sql.Date;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * ������ �� �������, ������� ��������� ������
 * 
 * <p>Java class for ClientType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ClientType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="ClientUID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ClientID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ClientCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ClientCodeCrm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FinalRiskLevel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FullName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LastName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FirstName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Patronymic" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BirthDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="PlaceOfBirth" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Sex" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Citizenship" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="INN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PinFl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Document" type="{http://Document.NFO.ru}Document" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Address" type="{http://NFOCommon.NFO.ru}AddressType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="RegAddrEqualsResAddr" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="IsCoBorrowed" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Phone" type="{http://NFOCommon.NFO.ru}PhoneType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="JobInfo" type="{http://NFOCommon.NFO.ru}JobInfoType" minOccurs="0"/>
 *         &lt;element name="IsAdditionalIncome" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="AdditionalIncome" type="{http://NFOCommon.NFO.ru}AdditionalIncomeType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="IsCar" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="IsRealEstate" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="DepositInfo" type="{http://NFOCommon.NFO.ru}DepositInfoType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="MaritalStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ChildrenNum0To3" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="ChildrenNum3To16" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="AdultChildrenNum" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="Education" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TypeOfHousing" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IsRetiree" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="NinpsAccountBank" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CurrentLoan" type="{http://NFOCommon.NFO.ru}CurrentLoanType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="RelatedPerson" type="{http://RelatedPerson.NFO.ru}RelatedPerson" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClientType", namespace = "http://Client.NFO.ru", propOrder = {
    "id",
    "clientUID",
    "clientID",
    "clientCode",
    "clientCodeCrm",
    "finalRiskLevel",
    "fullName",
    "lastName",
    "firstName",
    "patronymic",
    "birthDate",
    "placeOfBirth",
    "sex",
    "citizenship",
    "inn",
    "pinFl",
    "document",
    "address",
    "regAddrEqualsResAddr",
    "isCoBorrowed",
    "phone",
    "jobInfo",
    "isAdditionalIncome",
    "additionalIncome",
    "isCar",
    "isRealEstate",
    "depositInfo",
    "maritalStatus",
    "childrenNum0To3",
    "childrenNum3To16",
    "adultChildrenNum",
    "education",
    "typeOfHousing",
    "isRetiree",
    "ninpsAccountBank",
    "currentLoan",
    "relatedPerson"
})
public class ClientType {

    @XmlElement(name = "Id")
    protected BigInteger id;
    @XmlElement(name = "ClientUID")
    protected String clientUID;
    @XmlElement(name = "ClientID")
    protected String clientID;
    @XmlElement(name = "ClientCode")
    protected String clientCode;
    @XmlElement(name = "ClientCodeCrm")
    protected String clientCodeCrm;
    @XmlElement(name = "FinalRiskLevel")
    protected String finalRiskLevel;
    @XmlElement(name = "FullName")
    protected String fullName;
    @XmlElement(name = "LastName")
    protected String lastName;
    @XmlElement(name = "FirstName")
    protected String firstName;
    @XmlElement(name = "Patronymic")
    protected String patronymic;
    @XmlElement(name = "BirthDate", type = String.class)
    @XmlJavaTypeAdapter(Adapter2 .class)
    @XmlSchemaType(name = "date")
    protected Date birthDate;
    @XmlElement(name = "PlaceOfBirth")
    protected String placeOfBirth;
    @XmlElement(name = "Sex")
    protected String sex;
    @XmlElement(name = "Citizenship")
    protected String citizenship;
    @XmlElement(name = "INN")
    protected String inn;
    @XmlElement(name = "PinFl")
    protected String pinFl;
    @XmlElement(name = "Document")
    protected List<Document> document;
    @XmlElement(name = "Address")
    protected List<AddressType> address;
    @XmlElement(name = "RegAddrEqualsResAddr")
    protected Boolean regAddrEqualsResAddr;
    @XmlElement(name = "IsCoBorrowed")
    protected Boolean isCoBorrowed;
    @XmlElement(name = "Phone")
    protected List<PhoneType> phone;
    @XmlElement(name = "JobInfo")
    protected JobInfoType jobInfo;
    @XmlElement(name = "IsAdditionalIncome")
    protected Boolean isAdditionalIncome;
    @XmlElement(name = "AdditionalIncome")
    protected List<AdditionalIncomeType> additionalIncome;
    @XmlElement(name = "IsCar")
    protected Boolean isCar;
    @XmlElement(name = "IsRealEstate")
    protected Boolean isRealEstate;
    @XmlElement(name = "DepositInfo")
    protected List<DepositInfoType> depositInfo;
    @XmlElement(name = "MaritalStatus")
    protected String maritalStatus;
    @XmlElement(name = "ChildrenNum0To3")
    protected BigInteger childrenNum0To3;
    @XmlElement(name = "ChildrenNum3To16")
    protected BigInteger childrenNum3To16;
    @XmlElement(name = "AdultChildrenNum")
    protected BigInteger adultChildrenNum;
    @XmlElement(name = "Education")
    protected String education;
    @XmlElement(name = "TypeOfHousing")
    protected String typeOfHousing;
    @XmlElement(name = "IsRetiree")
    protected Boolean isRetiree;
    @XmlElement(name = "NinpsAccountBank")
    protected String ninpsAccountBank;
    @XmlElement(name = "CurrentLoan")
    protected List<CurrentLoanType> currentLoan;
    @XmlElement(name = "RelatedPerson")
    protected List<RelatedPerson> relatedPerson;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the clientUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientUID() {
        return clientUID;
    }

    /**
     * Sets the value of the clientUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientUID(String value) {
        this.clientUID = value;
    }

    /**
     * Gets the value of the clientID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientID() {
        return clientID;
    }

    /**
     * Sets the value of the clientID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientID(String value) {
        this.clientID = value;
    }

    /**
     * Gets the value of the clientCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientCode() {
        return clientCode;
    }

    /**
     * Sets the value of the clientCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientCode(String value) {
        this.clientCode = value;
    }

    /**
     * Gets the value of the clientCodeCrm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientCodeCrm() {
        return clientCodeCrm;
    }

    /**
     * Sets the value of the clientCodeCrm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientCodeCrm(String value) {
        this.clientCodeCrm = value;
    }

    /**
     * Gets the value of the finalRiskLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFinalRiskLevel() {
        return finalRiskLevel;
    }

    /**
     * Sets the value of the finalRiskLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFinalRiskLevel(String value) {
        this.finalRiskLevel = value;
    }

    /**
     * Gets the value of the fullName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * Sets the value of the fullName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFullName(String value) {
        this.fullName = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the patronymic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatronymic() {
        return patronymic;
    }

    /**
     * Sets the value of the patronymic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatronymic(String value) {
        this.patronymic = value;
    }

    /**
     * Gets the value of the birthDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getBirthDate() {
        return birthDate;
    }

    /**
     * Sets the value of the birthDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBirthDate(Date value) {
        this.birthDate = value;
    }

    /**
     * Gets the value of the placeOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlaceOfBirth() {
        return placeOfBirth;
    }

    /**
     * Sets the value of the placeOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlaceOfBirth(String value) {
        this.placeOfBirth = value;
    }

    /**
     * Gets the value of the sex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSex() {
        return sex;
    }

    /**
     * Sets the value of the sex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSex(String value) {
        this.sex = value;
    }

    /**
     * Gets the value of the citizenship property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCitizenship() {
        return citizenship;
    }

    /**
     * Sets the value of the citizenship property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCitizenship(String value) {
        this.citizenship = value;
    }

    /**
     * Gets the value of the inn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINN() {
        return inn;
    }

    /**
     * Sets the value of the inn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINN(String value) {
        this.inn = value;
    }

    /**
     * Gets the value of the pinFl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPinFl() {
        return pinFl;
    }

    /**
     * Sets the value of the pinFl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPinFl(String value) {
        this.pinFl = value;
    }

    /**
     * Gets the value of the document property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the document property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocument().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Document }
     * 
     * 
     */
    public List<Document> getDocument() {
        if (document == null) {
            document = new ArrayList<Document>();
        }
        return this.document;
    }

    /**
     * Gets the value of the address property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the address property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddress().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AddressType }
     * 
     * 
     */
    public List<AddressType> getAddress() {
        if (address == null) {
            address = new ArrayList<AddressType>();
        }
        return this.address;
    }

    /**
     * Gets the value of the regAddrEqualsResAddr property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getRegAddrEqualsResAddr() {
        return regAddrEqualsResAddr;
    }

    /**
     * Sets the value of the regAddrEqualsResAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRegAddrEqualsResAddr(Boolean value) {
        this.regAddrEqualsResAddr = value;
    }

    /**
     * Gets the value of the isCoBorrowed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getIsCoBorrowed() {
        return isCoBorrowed;
    }

    /**
     * Sets the value of the isCoBorrowed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsCoBorrowed(Boolean value) {
        this.isCoBorrowed = value;
    }

    /**
     * Gets the value of the phone property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the phone property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPhone().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PhoneType }
     * 
     * 
     */
    public List<PhoneType> getPhone() {
        if (phone == null) {
            phone = new ArrayList<PhoneType>();
        }
        return this.phone;
    }

    /**
     * Gets the value of the jobInfo property.
     * 
     * @return
     *     possible object is
     *     {@link JobInfoType }
     *     
     */
    public JobInfoType getJobInfo() {
        return jobInfo;
    }

    /**
     * Sets the value of the jobInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link JobInfoType }
     *     
     */
    public void setJobInfo(JobInfoType value) {
        this.jobInfo = value;
    }

    /**
     * Gets the value of the isAdditionalIncome property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getIsAdditionalIncome() {
        return isAdditionalIncome;
    }

    /**
     * Sets the value of the isAdditionalIncome property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsAdditionalIncome(Boolean value) {
        this.isAdditionalIncome = value;
    }

    /**
     * Gets the value of the additionalIncome property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionalIncome property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionalIncome().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdditionalIncomeType }
     * 
     * 
     */
    public List<AdditionalIncomeType> getAdditionalIncome() {
        if (additionalIncome == null) {
            additionalIncome = new ArrayList<AdditionalIncomeType>();
        }
        return this.additionalIncome;
    }

    /**
     * Gets the value of the isCar property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getIsCar() {
        return isCar;
    }

    /**
     * Sets the value of the isCar property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsCar(Boolean value) {
        this.isCar = value;
    }

    /**
     * Gets the value of the isRealEstate property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getIsRealEstate() {
        return isRealEstate;
    }

    /**
     * Sets the value of the isRealEstate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsRealEstate(Boolean value) {
        this.isRealEstate = value;
    }

    /**
     * Gets the value of the depositInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the depositInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDepositInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DepositInfoType }
     * 
     * 
     */
    public List<DepositInfoType> getDepositInfo() {
        if (depositInfo == null) {
            depositInfo = new ArrayList<DepositInfoType>();
        }
        return this.depositInfo;
    }

    /**
     * Gets the value of the maritalStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaritalStatus() {
        return maritalStatus;
    }

    /**
     * Sets the value of the maritalStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaritalStatus(String value) {
        this.maritalStatus = value;
    }

    /**
     * Gets the value of the childrenNum0To3 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getChildrenNum0To3() {
        return childrenNum0To3;
    }

    /**
     * Sets the value of the childrenNum0To3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setChildrenNum0To3(BigInteger value) {
        this.childrenNum0To3 = value;
    }

    /**
     * Gets the value of the childrenNum3To16 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getChildrenNum3To16() {
        return childrenNum3To16;
    }

    /**
     * Sets the value of the childrenNum3To16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setChildrenNum3To16(BigInteger value) {
        this.childrenNum3To16 = value;
    }

    /**
     * Gets the value of the adultChildrenNum property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAdultChildrenNum() {
        return adultChildrenNum;
    }

    /**
     * Sets the value of the adultChildrenNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAdultChildrenNum(BigInteger value) {
        this.adultChildrenNum = value;
    }

    /**
     * Gets the value of the education property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEducation() {
        return education;
    }

    /**
     * Sets the value of the education property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEducation(String value) {
        this.education = value;
    }

    /**
     * Gets the value of the typeOfHousing property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeOfHousing() {
        return typeOfHousing;
    }

    /**
     * Sets the value of the typeOfHousing property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeOfHousing(String value) {
        this.typeOfHousing = value;
    }

    /**
     * Gets the value of the isRetiree property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getIsRetiree() {
        return isRetiree;
    }

    /**
     * Sets the value of the isRetiree property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsRetiree(Boolean value) {
        this.isRetiree = value;
    }

    /**
     * Gets the value of the ninpsAccountBank property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNinpsAccountBank() {
        return ninpsAccountBank;
    }

    /**
     * Sets the value of the ninpsAccountBank property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNinpsAccountBank(String value) {
        this.ninpsAccountBank = value;
    }

    /**
     * Gets the value of the currentLoan property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the currentLoan property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCurrentLoan().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CurrentLoanType }
     * 
     * 
     */
    public List<CurrentLoanType> getCurrentLoan() {
        if (currentLoan == null) {
            currentLoan = new ArrayList<CurrentLoanType>();
        }
        return this.currentLoan;
    }

    /**
     * Gets the value of the relatedPerson property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relatedPerson property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelatedPerson().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RelatedPerson }
     * 
     * 
     */
    public List<RelatedPerson> getRelatedPerson() {
        if (relatedPerson == null) {
            relatedPerson = new ArrayList<RelatedPerson>();
        }
        return this.relatedPerson;
    }

    public void setDocument(List<Document> value) {
        this.document = value;
    }

    public void setAddress(List<AddressType> value) {
        this.address = value;
    }

    public void setPhone(List<PhoneType> value) {
        this.phone = value;
    }

    public void setAdditionalIncome(List<AdditionalIncomeType> value) {
        this.additionalIncome = value;
    }

    public void setDepositInfo(List<DepositInfoType> value) {
        this.depositInfo = value;
    }

    public void setCurrentLoan(List<CurrentLoanType> value) {
        this.currentLoan = value;
    }

    public void setRelatedPerson(List<RelatedPerson> value) {
        this.relatedPerson = value;
    }

}
