//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.17 at 09:26:02 PM MSK 
//


package ru.digitalspirit.asaka.microzime.model;

import java.sql.Date;
import javax.xml.bind.annotation.adapters.XmlAdapter;

public class Adapter2
    extends XmlAdapter<String, Date>
{


    public Date unmarshal(String value) {
        return (ru.digitalspirit.asaka.microzime.util.DateTypeConverter.parseDate(value));
    }

    public String marshal(Date value) {
        return (ru.digitalspirit.asaka.microzime.util.DateTypeConverter.printDate(value));
    }

}
