//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.17 at 09:26:02 PM MSK 
//


package ru.digitalspirit.asaka.microzime.model;

import java.math.BigInteger;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for Application complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Application">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ApplicationID" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="ClaimNumBpm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ClaimNumCrm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Branch" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ClaimDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="Client" type="{http://Client.NFO.ru}ClientType" minOccurs="0"/>
 *         &lt;element name="Loan" type="{http://Loan.NFO.ru}LoanType" minOccurs="0"/>
 *         &lt;element name="AdditionalContact" type="{http://NFOCommon.NFO.ru}AdditionalContactType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ManagerName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AttachedDocuments" type="{http://AttachedDocument.NFO.ru}AttachedDocument" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ApplicationHistory" type="{http://ApplicationHistory.NFO.ru}ApplicationHistory" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Application", namespace = "http://Microzime.NFO.ru", propOrder = {
    "applicationID",
    "claimNumBpm",
    "claimNumCrm",
    "branch",
    "status",
    "claimDate",
    "client",
    "loan",
    "additionalContact",
    "managerName",
    "attachedDocuments",
    "applicationHistory"
})
public class Application {

    @XmlElement(name = "ApplicationID")
    protected BigInteger applicationID;
    @XmlElement(name = "ClaimNumBpm")
    protected String claimNumBpm;
    @XmlElement(name = "ClaimNumCrm")
    protected String claimNumCrm;
    @XmlElement(name = "Branch")
    protected String branch;
    @XmlElement(name = "Status")
    protected String status;
    @XmlElement(name = "ClaimDate", type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "dateTime")
    protected Timestamp claimDate;
    @XmlElement(name = "Client")
    protected ClientType client;
    @XmlElement(name = "Loan")
    protected LoanType loan;
    @XmlElement(name = "AdditionalContact")
    protected List<AdditionalContactType> additionalContact;
    @XmlElement(name = "ManagerName")
    protected String managerName;
    @XmlElement(name = "AttachedDocuments")
    protected List<AttachedDocument> attachedDocuments;
    @XmlElement(name = "ApplicationHistory")
    protected List<ApplicationHistory> applicationHistory;

    /**
     * Gets the value of the applicationID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getApplicationID() {
        return applicationID;
    }

    /**
     * Sets the value of the applicationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setApplicationID(BigInteger value) {
        this.applicationID = value;
    }

    /**
     * Gets the value of the claimNumBpm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClaimNumBpm() {
        return claimNumBpm;
    }

    /**
     * Sets the value of the claimNumBpm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClaimNumBpm(String value) {
        this.claimNumBpm = value;
    }

    /**
     * Gets the value of the claimNumCrm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClaimNumCrm() {
        return claimNumCrm;
    }

    /**
     * Sets the value of the claimNumCrm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClaimNumCrm(String value) {
        this.claimNumCrm = value;
    }

    /**
     * Gets the value of the branch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBranch() {
        return branch;
    }

    /**
     * Sets the value of the branch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBranch(String value) {
        this.branch = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the claimDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Timestamp getClaimDate() {
        return claimDate;
    }

    /**
     * Sets the value of the claimDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClaimDate(Timestamp value) {
        this.claimDate = value;
    }

    /**
     * Gets the value of the client property.
     * 
     * @return
     *     possible object is
     *     {@link ClientType }
     *     
     */
    public ClientType getClient() {
        return client;
    }

    /**
     * Sets the value of the client property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClientType }
     *     
     */
    public void setClient(ClientType value) {
        this.client = value;
    }

    /**
     * Gets the value of the loan property.
     * 
     * @return
     *     possible object is
     *     {@link LoanType }
     *     
     */
    public LoanType getLoan() {
        return loan;
    }

    /**
     * Sets the value of the loan property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoanType }
     *     
     */
    public void setLoan(LoanType value) {
        this.loan = value;
    }

    /**
     * Gets the value of the additionalContact property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionalContact property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionalContact().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdditionalContactType }
     * 
     * 
     */
    public List<AdditionalContactType> getAdditionalContact() {
        if (additionalContact == null) {
            additionalContact = new ArrayList<AdditionalContactType>();
        }
        return this.additionalContact;
    }

    /**
     * Gets the value of the managerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManagerName() {
        return managerName;
    }

    /**
     * Sets the value of the managerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManagerName(String value) {
        this.managerName = value;
    }

    /**
     * Gets the value of the attachedDocuments property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attachedDocuments property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttachedDocuments().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AttachedDocument }
     * 
     * 
     */
    public List<AttachedDocument> getAttachedDocuments() {
        if (attachedDocuments == null) {
            attachedDocuments = new ArrayList<AttachedDocument>();
        }
        return this.attachedDocuments;
    }

    /**
     * Gets the value of the applicationHistory property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the applicationHistory property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getApplicationHistory().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ApplicationHistory }
     * 
     * 
     */
    public List<ApplicationHistory> getApplicationHistory() {
        if (applicationHistory == null) {
            applicationHistory = new ArrayList<ApplicationHistory>();
        }
        return this.applicationHistory;
    }

    public void setAdditionalContact(List<AdditionalContactType> value) {
        this.additionalContact = value;
    }

    public void setAttachedDocuments(List<AttachedDocument> value) {
        this.attachedDocuments = value;
    }

    public void setApplicationHistory(List<ApplicationHistory> value) {
        this.applicationHistory = value;
    }

}
