//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.17 at 09:26:02 PM MSK 
//


package ru.digitalspirit.asaka.microzime.model;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.sql.Date;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Сведения о запрашиваемом кредите
 * 
 * <p>Java class for LoanType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LoanType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="LoanProduct" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ProductId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Sum" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="LoanPurpose" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TermInMonth" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="InterestRate" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="RepaymentDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="RepaymentType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CollateralType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PaymentFromCreditFunds" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="PaymentFromOwnFunds" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Currency" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MinInterestRate" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="MaxInterestRate" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="FacilitiesForRepaymentDate" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="MaxDeferralRepaymentPeriod" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="InitialPayment" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="MinInitialPaymentPercent" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="MaxInitialPaymentPercent" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="CreditType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LoanType", namespace = "http://Loan.NFO.ru", propOrder = {
    "id",
    "loanProduct",
    "productId",
    "sum",
    "loanPurpose",
    "termInMonth",
    "interestRate",
    "repaymentDate",
    "repaymentType",
    "collateralType",
    "paymentFromCreditFunds",
    "paymentFromOwnFunds",
    "currency",
    "minInterestRate",
    "maxInterestRate",
    "facilitiesForRepaymentDate",
    "maxDeferralRepaymentPeriod",
    "initialPayment",
    "minInitialPaymentPercent",
    "maxInitialPaymentPercent",
    "creditType"
})
public class LoanType {

    protected BigInteger id;
    @XmlElement(name = "LoanProduct")
    protected String loanProduct;
    @XmlElement(name = "ProductId")
    protected String productId;
    @XmlElement(name = "Sum")
    protected BigDecimal sum;
    @XmlElement(name = "LoanPurpose")
    protected String loanPurpose;
    @XmlElement(name = "TermInMonth")
    protected BigInteger termInMonth;
    @XmlElement(name = "InterestRate")
    protected BigDecimal interestRate;
    @XmlElement(name = "RepaymentDate", type = String.class)
    @XmlJavaTypeAdapter(Adapter2 .class)
    @XmlSchemaType(name = "date")
    protected Date repaymentDate;
    @XmlElement(name = "RepaymentType")
    protected String repaymentType;
    @XmlElement(name = "CollateralType")
    protected String collateralType;
    @XmlElement(name = "PaymentFromCreditFunds")
    protected Boolean paymentFromCreditFunds;
    @XmlElement(name = "PaymentFromOwnFunds")
    protected Boolean paymentFromOwnFunds;
    @XmlElement(name = "Currency")
    protected String currency;
    @XmlElement(name = "MinInterestRate")
    protected BigDecimal minInterestRate;
    @XmlElement(name = "MaxInterestRate")
    protected BigDecimal maxInterestRate;
    @XmlElement(name = "FacilitiesForRepaymentDate")
    protected Boolean facilitiesForRepaymentDate;
    @XmlElement(name = "MaxDeferralRepaymentPeriod")
    protected BigInteger maxDeferralRepaymentPeriod;
    @XmlElement(name = "InitialPayment")
    protected BigDecimal initialPayment;
    @XmlElement(name = "MinInitialPaymentPercent")
    protected BigDecimal minInitialPaymentPercent;
    @XmlElement(name = "MaxInitialPaymentPercent")
    protected BigDecimal maxInitialPaymentPercent;
    @XmlElement(name = "CreditType")
    protected String creditType;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the loanProduct property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoanProduct() {
        return loanProduct;
    }

    /**
     * Sets the value of the loanProduct property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoanProduct(String value) {
        this.loanProduct = value;
    }

    /**
     * Gets the value of the productId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductId() {
        return productId;
    }

    /**
     * Sets the value of the productId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductId(String value) {
        this.productId = value;
    }

    /**
     * Gets the value of the sum property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSum() {
        return sum;
    }

    /**
     * Sets the value of the sum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSum(BigDecimal value) {
        this.sum = value;
    }

    /**
     * Gets the value of the loanPurpose property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoanPurpose() {
        return loanPurpose;
    }

    /**
     * Sets the value of the loanPurpose property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoanPurpose(String value) {
        this.loanPurpose = value;
    }

    /**
     * Gets the value of the termInMonth property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTermInMonth() {
        return termInMonth;
    }

    /**
     * Sets the value of the termInMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTermInMonth(BigInteger value) {
        this.termInMonth = value;
    }

    /**
     * Gets the value of the interestRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInterestRate() {
        return interestRate;
    }

    /**
     * Sets the value of the interestRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInterestRate(BigDecimal value) {
        this.interestRate = value;
    }

    /**
     * Gets the value of the repaymentDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getRepaymentDate() {
        return repaymentDate;
    }

    /**
     * Sets the value of the repaymentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepaymentDate(Date value) {
        this.repaymentDate = value;
    }

    /**
     * Gets the value of the repaymentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepaymentType() {
        return repaymentType;
    }

    /**
     * Sets the value of the repaymentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepaymentType(String value) {
        this.repaymentType = value;
    }

    /**
     * Gets the value of the collateralType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCollateralType() {
        return collateralType;
    }

    /**
     * Sets the value of the collateralType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCollateralType(String value) {
        this.collateralType = value;
    }

    /**
     * Gets the value of the paymentFromCreditFunds property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getPaymentFromCreditFunds() {
        return paymentFromCreditFunds;
    }

    /**
     * Sets the value of the paymentFromCreditFunds property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPaymentFromCreditFunds(Boolean value) {
        this.paymentFromCreditFunds = value;
    }

    /**
     * Gets the value of the paymentFromOwnFunds property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getPaymentFromOwnFunds() {
        return paymentFromOwnFunds;
    }

    /**
     * Sets the value of the paymentFromOwnFunds property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPaymentFromOwnFunds(Boolean value) {
        this.paymentFromOwnFunds = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the minInterestRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMinInterestRate() {
        return minInterestRate;
    }

    /**
     * Sets the value of the minInterestRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMinInterestRate(BigDecimal value) {
        this.minInterestRate = value;
    }

    /**
     * Gets the value of the maxInterestRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMaxInterestRate() {
        return maxInterestRate;
    }

    /**
     * Sets the value of the maxInterestRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMaxInterestRate(BigDecimal value) {
        this.maxInterestRate = value;
    }

    /**
     * Gets the value of the facilitiesForRepaymentDate property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getFacilitiesForRepaymentDate() {
        return facilitiesForRepaymentDate;
    }

    /**
     * Sets the value of the facilitiesForRepaymentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFacilitiesForRepaymentDate(Boolean value) {
        this.facilitiesForRepaymentDate = value;
    }

    /**
     * Gets the value of the maxDeferralRepaymentPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxDeferralRepaymentPeriod() {
        return maxDeferralRepaymentPeriod;
    }

    /**
     * Sets the value of the maxDeferralRepaymentPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxDeferralRepaymentPeriod(BigInteger value) {
        this.maxDeferralRepaymentPeriod = value;
    }

    /**
     * Gets the value of the initialPayment property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInitialPayment() {
        return initialPayment;
    }

    /**
     * Sets the value of the initialPayment property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInitialPayment(BigDecimal value) {
        this.initialPayment = value;
    }

    /**
     * Gets the value of the minInitialPaymentPercent property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMinInitialPaymentPercent() {
        return minInitialPaymentPercent;
    }

    /**
     * Sets the value of the minInitialPaymentPercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMinInitialPaymentPercent(BigDecimal value) {
        this.minInitialPaymentPercent = value;
    }

    /**
     * Gets the value of the maxInitialPaymentPercent property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMaxInitialPaymentPercent() {
        return maxInitialPaymentPercent;
    }

    /**
     * Sets the value of the maxInitialPaymentPercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMaxInitialPaymentPercent(BigDecimal value) {
        this.maxInitialPaymentPercent = value;
    }

    /**
     * Gets the value of the creditType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditType() {
        return creditType;
    }

    /**
     * Sets the value of the creditType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditType(String value) {
        this.creditType = value;
    }

}
