//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.17 at 09:26:02 PM MSK 
//


package ru.digitalspirit.asaka.microzime.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.digitalspirit.asaka.microzime.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.digitalspirit.asaka.microzime.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Application }
     * 
     */
    public Application createApplication() {
        return new Application();
    }

    /**
     * Create an instance of {@link ClientType }
     * 
     */
    public ClientType createClientType() {
        return new ClientType();
    }

    /**
     * Create an instance of {@link TrusteeStatusType }
     * 
     */
    public TrusteeStatusType createTrusteeStatusType() {
        return new TrusteeStatusType();
    }

    /**
     * Create an instance of {@link PhoneListType }
     * 
     */
    public PhoneListType createPhoneListType() {
        return new PhoneListType();
    }

    /**
     * Create an instance of {@link EmailType }
     * 
     */
    public EmailType createEmailType() {
        return new EmailType();
    }

    /**
     * Create an instance of {@link AddressListType }
     * 
     */
    public AddressListType createAddressListType() {
        return new AddressListType();
    }

    /**
     * Create an instance of {@link AdditionalContactType }
     * 
     */
    public AdditionalContactType createAdditionalContactType() {
        return new AdditionalContactType();
    }

    /**
     * Create an instance of {@link AccountType }
     * 
     */
    public AccountType createAccountType() {
        return new AccountType();
    }

    /**
     * Create an instance of {@link DepositInfoType }
     * 
     */
    public DepositInfoType createDepositInfoType() {
        return new DepositInfoType();
    }

    /**
     * Create an instance of {@link CurrentLoanType }
     * 
     */
    public CurrentLoanType createCurrentLoanType() {
        return new CurrentLoanType();
    }

    /**
     * Create an instance of {@link CommentType }
     * 
     */
    public CommentType createCommentType() {
        return new CommentType();
    }

    /**
     * Create an instance of {@link PhoneType }
     * 
     */
    public PhoneType createPhoneType() {
        return new PhoneType();
    }

    /**
     * Create an instance of {@link AdditionalIncomeType }
     * 
     */
    public AdditionalIncomeType createAdditionalIncomeType() {
        return new AdditionalIncomeType();
    }

    /**
     * Create an instance of {@link AccountListType }
     * 
     */
    public AccountListType createAccountListType() {
        return new AccountListType();
    }

    /**
     * Create an instance of {@link NotificationType }
     * 
     */
    public NotificationType createNotificationType() {
        return new NotificationType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link AppSystemIDType }
     * 
     */
    public AppSystemIDType createAppSystemIDType() {
        return new AppSystemIDType();
    }

    /**
     * Create an instance of {@link EmailListType }
     * 
     */
    public EmailListType createEmailListType() {
        return new EmailListType();
    }

    /**
     * Create an instance of {@link CurrencyType }
     * 
     */
    public CurrencyType createCurrencyType() {
        return new CurrencyType();
    }

    /**
     * Create an instance of {@link JobInfoType }
     * 
     */
    public JobInfoType createJobInfoType() {
        return new JobInfoType();
    }

    /**
     * Create an instance of {@link CustomerIDType }
     * 
     */
    public CustomerIDType createCustomerIDType() {
        return new CustomerIDType();
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link RelatedPerson }
     * 
     */
    public RelatedPerson createRelatedPerson() {
        return new RelatedPerson();
    }

    /**
     * Create an instance of {@link LoanType }
     * 
     */
    public LoanType createLoanType() {
        return new LoanType();
    }

    /**
     * Create an instance of {@link AttachedDocument }
     * 
     */
    public AttachedDocument createAttachedDocument() {
        return new AttachedDocument();
    }

    /**
     * Create an instance of {@link ApplicationHistory }
     * 
     */
    public ApplicationHistory createApplicationHistory() {
        return new ApplicationHistory();
    }

}
