//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.23 at 05:33:51 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://NFOCommon.NFO.ru", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.digitalspirit.asaka.microloan.model;
