package ru.digitalspirit.asaka.bpm.model.process;

public enum ProcessState {

	STATE_COMPENSATED,
    STATE_COMPENSATION_FAILED,
    STATE_COMPENSATING,
    STATE_DELETED,
    STATE_FAILED,
    STATE_FAILING,
    STATE_FINISHED,
    STATE_INDOUBT,
    STATE_READY,
    STATE_RUNNING,
    STATE_SUSPENDED,
    STATE_TERMINATED,
    STATE_TERMINATING
	
}
